variables:
  USER_PROJECT: "onlineshop"
  IMAGE_TAG: "$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TAG"

stages:
  - build
  - deploy
build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - docker build -t $IMAGE_TAG .
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - >
      sudo su $USER_PROJECT -c "
      docker rm -f $CI_PROJECT_NAME &&
      docker run --name $CI_PROJECT_NAME -dp $BE_PORT $IMAGE_TAG
      "
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags
