FROM mcr.microsoft.com/dotnet/sdk:6.0 as build

ARG SONAR_PROJECT_KEY=java-project
ARG SONAR_PROJECT_NAME=java-project
ARG SONAR_HOST_URL=http://192.168.252.163
ARG SONAR_TOKEN=sqa_8a4001cc2e3fa57947bb597e78957cca9c8cc134
ARG SONAR_VERSION=V1.0.0

WORKDIR /app

# Install Sonar Scanner, Coverlet and Java (required for Sonar Scanner)
RUN apt-get update && apt-get install -y openjdk-11-jdk
RUN dotnet tool install --global dotnet-sonarscanner
RUN dotnet tool install --global coverlet.console
ENV PATH="$PATH:/root/.dotnet/tools"

# Start Sonar Scanner
RUN dotnet sonarscanner begin \
  /k:"$SONAR_PROJECT_KEY" \
  /o:"$SONAR_PROJECT_NAME" \
  /d:sonar.host.url="$SONAR_HOST_URL" \
  /d:sonar.login="$SONAR_TOKEN" \
  /d:sonar.cs.opencover.reportsPaths=/coverage.opencover.xml \
  /v:"$SONAR_VERSION" \
  /d:sonar.qualitygate.wait=true

# Restore NuGet packages
COPY . .
RUN dotnet restore

# Copy the rest of the files over
#COPY . .

# Build and test the application
RUN dotnet publish --output /out/
RUN dotnet test \
  /p:CollectCoverage=true \
  /p:CoverletOutputFormat=opencover \
  /p:CoverletOutput="/coverage"

# End Sonar Scanner
RUN dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"


